baseURL: "https://Aohk22.github.io/workshop-report/"
relativeURLs: true
canonifyURLs: true
theme: "hugo-theme-learn"

security:
  enableInlineShortcodes: true

outputs:
  home: ["HTML", "RSS", "JSON"]

params:
  themeVariant: "workshop"
  editURL: ""
  description: ""
  author: "tukhoaluu123123@gmail.com"
  showVisitedLinks: true
  disableBreadcrumb: false
  disableNextPrev: false

languages:
  en:
    title: "Internship Report"
    weight: 1
    languageName: "English"
    menu:
      shortcuts:
        - name: "<i class='fab fa-facebook'></i> AWS Study Group"
          identifier: "AWS Study Group FB"
          url: "https://www.facebook.com/groups/awsstudygroupfcj/"
          weight: 20

  vi:
    title: "Báo cáo thực tập"
    weight: 2
    languageName: "Tiếng Việt"
    menu:
      shortcuts:
        - name: "<i class='fab fa-facebook'></i> AWS Study Group"
          identifier: "AWS Study Group FB"
          url: "https://www.facebook.com/groups/awsstudygroupfcj/"
          weight: 20

markup:
  goldmark:
    renderer:
      unsafe: true
